### ISSUE TITLE
Unable to read any method from IxloadRobot.py to any robot

### ISSUE THREAD

**Issue by rh00454289** [OpenIxia/IxLoad#2]
Trying to run the sample code provided with the changes required like IPaddress, Port and version.

However whenever i run the robot file then i get error as below.

20190410 00:16:09.932 : FAIL : No keyword with name 'connect' found.

Looks like it's not able read any python methods from IxloadRobot.py.

Kindly suggest at earliest.

**Comment by hubertgee** [comment]
This is a late response.  Sorry about that.  For the ixLoadRobot.py script, please open a support case with support.ix@keysight.com.  You could also try this Robot file: 

/IxLoad/RestApi/Python/SampleScripts/LoadSavedConfigFile/LoadConfigFile.robot

Open a new issue against this Robot script if you encounter a problem.
